### ISSUE TITLE
Client always times out

### ISSUE THREAD

**Issue by alwhiting** [Bugs5382/node-hl7-client#169]
Perhaps I'm missing something here; but the block starting at this line seems to be causing the client to constantly be reconnecting:
https://github.com/Bugs5382/node-hl7-client/blob/dcc0f10324582f1632a25ad1614a264346db6988/src/client/connection.ts#L323

Is there something that should be done to prevent this behavior? It's not possible to set the connectionTimeout to 0 so this is basically constantly triggering a socket destruction and then the retry logic kicks in. Also the error comes up as "server disconnected" but in reality it is us, the client, who disconnected, which makes me think maybe this is unintentional.

**Comment by Bugs5382** [comment]
@alwhiting Just so you know I been expecting this myself recently. You might have nailed it. Let me work on it this weekend.

**Comment by Bugs5382** [comment]
@alwhiting  I just pushed the changed into the develop branch. There should be a NPM that you should test out prior to me releasing it. I have to do some other internal testing, a lot of other series of tests that I run through not on any CI since this deals with medical applications. So let me know how your testing. By Monday, I will release on main.

**Comment by alwhiting** [comment]
I have been working around it with this hack for now:
```class ClientBugWorkaround extends Client {
    constructor(opts: ClientOptions) {
        const copy = JSON.parse(JSON.stringify(opts));
        copy.connectionTimeout = 1000;
        super(copy);
        this._opt.connectionTimeout = opts.connectionTimeout || 0;
    }
}```

That got around the normalize function enforcing a timeout; when it's set to 0 the timeout that was killing the socket was not run.

**Comment by Bugs5382** [comment]
What’s the PR for this intergrated into the code?

**Comment by Bugs5382** [comment]
@alwhiting Add it to PR #176  please :)

**Comment by alwhiting** [comment]
> @alwhiting Add it to PR #176 please :)

I didn't actually fork this one just did the hack I pasted above in my code so I could bypass the minimum value for the `connectionTimeout` option. In the short term I think you could allow that to be set to 0 instead of a minimum of 1000ms. In the longer term I think investigating why that interval exists that calls `socket.destroy()` is even there... maybe there is a reason for it but I'm not sure what.

**Comment by Bugs5382** [comment]
sweet. I have already done that in develop:

https://github.com/Bugs5382/node-hl7-client/blob/e66b85ae28068875c2407113dfe08df0d15d9e9e/src/utils/normalizedClient.ts#L17

https://github.com/Bugs5382/node-hl7-client/blob/e66b85ae28068875c2407113dfe08df0d15d9e9e/src/utils/normalizedClient.ts#L163

and now its working like designed. codec is fixed in the node-hl7-package. merging in.
