### ISSUE TITLE
fix: MSH.9.3 in acknowledgment incorrectly formatted for hl7 spec 2.4+

### ISSUE THREAD

**Issue by jtarvainen** [Bugs5382/node-hl7-client#93]
For an acknowledgment message using the HL7 2.5.1 specification, the MSH.9.3 subfield is set to the values of MSH.9.1 and MSH.9.2, separated by an underscore:

https://github.com/Bugs5382/node-hl7-client/blob/eee724ed7d68d3f578a895a046e8302e96829ba4/src/specification/2.4.ts#L80

We have a device that uses HL7 2.5.1 but expects the MSH.9.3 subfield to contain only the MSH.9.1 value. For example, it expects the MSH.9 field to have the format "ACK^R22^ACK", but `node-hl7-client` sets the value to "ACK^R22^ACK_R22", which is not accepted.

Could you please check if the formulation of the MSH.9.3 subfield in `node-hl7-client` is correct? If it is, then there would need to be some way to bypass the default field value when constructing the acknowledgment message.

Thanks!

**Comment by Bugs5382** [comment]
@jtarvainen Ok... So this is what I used as my reference:

On [this page](https://hl7-definition.caristix.com/v2/HL7v2.5.1/Fields/MSH.9) MSH.9.1 through MSH9.3 are all required.  For [MSH9.3](https://hl7-definition.caristix.com/v2/HL7v2.5.1/Fields/MSH.9.3) it says:

> Specifies the abstract message structure code. Refer to HL7 Table 0354 - Message Structure in section 2.17.3 for valid values.

Table [0354](https://hl7-definition.caristix.com/v2/HL7v2.5.1/Tables/0354) shows that everything is 9.1 + 9.3 with the underscore as the value. I can see that just plain **ACK** is valid.

<img width="525" alt="image" src="https://github.com/Bugs5382/node-hl7-client/assets/12115015/9c684db7-01a9-4e61-9667-11c376705dd7">

ooops.

So, it looks like it only started being valid for 2.4 and beyond. Let me correct that. I will have to update the **node-hl7-server** package as well. I saw your comment there as well.

**Comment by Bugs5382** [comment]
@jtarvainen Please review the branch created:

https://github.com/Bugs5382/node-hl7-client/blob/7af097037e201b7fb63394ea757c2edf688a965c/src/specification/2.4.ts#L34-L37

Could you update the Spec to include 9.3? Optional.

https://github.com/Bugs5382/node-hl7-client/blob/7af097037e201b7fb63394ea757c2edf688a965c/src/specification/2.4.ts#L85-L88

If msh_9_3 is not passed over, it will do as it's been doing. Otherwise...

https://github.com/Bugs5382/node-hl7-client/blob/7af097037e201b7fb63394ea757c2edf688a965c/__tests__/hl7.build.test.ts#L154-L168

It can be overridden. I know I am working on the riddle of my node-hl7-server package since I use 2.7 as the default. Please confirm if this is what you are looking for.

**Comment by jtarvainen** [comment]
@Bugs5382 Thanks, that works for me!

**Comment by Bugs5382** [comment]
@jtarvainen Yep. Ok. Let me commit this here, so I can update the node-hl7-server package and update that documentation as well.

The node-hl7-server package uses this package to build it out.

**Comment by Bugs5382** [comment]
Release in node-hl7-client@2.1.1-beta.1. I brought that over into the node-hl7-server to work on that issue.

**Comment by Bugs5382** [comment]
@jtarvainen  Check out https://github.com/Bugs5382/node-hl7-server/issues/76#issuecomment-2145819831

**Comment by jtarvainen** [comment]
Looks good to me!

**Comment by Bugs5382** [comment]
@jtarvainen This package has been released! Be sure to leave me a star!
